### ISSUE TITLE
OpenMP and clang

### ISSUE THREAD

**Issue by muschellij2** [jonclayden/mmand#4] opened 2017-09-08 17:15 UTC
Issues with OSX clang (which does not support openmp and `-fopenmp` option), causes some errors with installation:
https://travis-ci.org/neuroconductor/mimosa/jobs/271315492 and https://travis-ci.org/muschellij2/mimosa/jobs/269751053.  

May want to add something to the effect of 
```
brew install gcc --without-multilib
```
with your installation.

**Comment by jonclayden** [comment] 2017-09-09 12:58
Thanks for the heads-up, John. I regularly build `mmand` on macOS, both with and without OpenMP-capable LLVM/clang, and I don't have any problems, but there may be some quirk in the Travis set-up that stops it from working. (I don't do Travis macOS builds routinely, only Linux.) Travis seems to have a macOS outage at the moment, but I'll look into it when their infrastructure comes back up.

**Comment by jonclayden** [comment] 2017-09-10 11:18
OK, I can [replicate this on Travis now](https://travis-ci.org/jonclayden/mmand/jobs/273459083), but this seems like a problem with the build environment rather than with `mmand` itself (cf. [this issue](https://github.com/travis-ci/travis-ci/issues/7820)). The Travis build environment may use CRAN R but not CRAN’s compilers, in which case the `make` environment may be inconsistent with the actual capabilities of the compiler. In essence, `SHLIB_OPENMP_CXXFLAGS` should evaluate empty, but it doesn’t. Perhaps @craigcitro or @jimhester could clarify.

**Comment by jonclayden** [comment] 2017-09-12 14:51
As I suspected, adding the following lines to the Travis config seems to be sufficient [to resolve the issue](https://travis-ci.org/jonclayden/mmand/jobs/274494229#L440):

    before_install:
      - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mkdir -p ~/.R && echo "SHLIB_OPENMP_CXXFLAGS = " >>~/.R/Makevars; fi

I'll suggest this for the default Travis configuration for R, unless you see any issue with this...?

**Comment by jimhester** [comment] 2017-09-12 21:33
I disagree, you will see the same failures if you try to compile `mmand` on any MacOS machine using the standard Xcode toolchain (which is almost all of them). The only time this will actually work is when a user has a newer version of clang that supports OpenMP, such as the one CRAN provides. But I suspect the number of users doing that is exceedingly small.

I think package authors are better off testing for OpenMP explicitly in their `configure` script or in Makevars rather than relying on `SHLIB_OPENMP_CXXFLAGS`, which will be wrong for the majority of users on MacOS.

**Comment by jonclayden** [comment] 2017-09-13 10:16
Thanks for your input, Jim. If this is the consensus then I will add a `configure` script to the package specifically to test for OpenMP support, but I would point out that

- use of `SHLIB_OPENMP_CXXFLAGS` is the route recommended by [Writing R extensions](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#OpenMP-support) for pre-C++11 code;
- CRAN builds of R for macOS prefer binary packages out of the box, and specifically state that their `clang` build is required for compiling packages from source; and
- Homebrew-installed R also does not support OpenMP, but does set `SHLIB_OPENMP_CXXFLAGS` empty (as would self-compiled R using the Xcode toolchain), and therefore works just fine.

I appreciate that theory and practice are two different things, but it still feels to me like the default Travis build environment should support the "official" approach.

**Comment by muschellij2** [comment] 2017-09-13 13:55
I don't know what the consensus is, but https://github.com/travis-ci/travis-ci/issues/7711 is relevant it seems and @jimhester has a PR https://github.com/elbamos/largeVis/pull/48 that seems like it should fix the problem.

Whether the problem should be "fixed" seems like it still needs to be decided and I'll leave it with you.

**Comment by jimhester** [comment] 2017-09-13 14:41
We are talking here about the MacOS version of travis, which uses R binaries supplied by CRAN (and compiled with their version of clang that has OpenMP support), which is why there is an inconsistency.

For linux builds we build R on travis as well, so there is no inconsistencies in the capabilities.

I have no plans of supporting CRANs custom clang toolchain on travis, the clang binaries are ~250MB and would take a fair amount of time to download for every build. However if you do want to go this route you should be able to do so using something like the following in your `.travis.yml`

```yaml
sudo: required

before_install: -|
  curl -LO http://r.research.att.com/libs/clang-4.0.0-darwin15.6-Release.tar.gz
  sudo tar fvxz clang-4.0.0-darwin15.6-Release.tar.gz -C /
```

**Comment by muschellij2** [comment] 2017-09-13 15:16
Ahh, understood and agree - I don't want to have to download CRAN `clang` as most users would use the Xcode workflow.  

For now, I'll use the resolution from https://github.com/jonclayden/mmand/issues/4#issuecomment-328877225 as I believe that 

1) `mmand` would work on CRAN (as OpenMP is supported on their `clang`)
2) `mmand` would compile for the standard MacOS user (as `SHLIB_OPENMP_CXXFLAGS` would be set to empty in their standard installation from the CRAN installer (not the binary)) - please let me know if I'm wrong
3) Will work on Travis and [you always need 3 bullet points](https://medium.com/lessons-from-mckinsey/the-rule-of-3-c1cd82dbc96e)

**Comment by jimhester** [comment] 2017-09-13 16:48
2. is not correct, `SHLIB_OPENMP_CXXFLAGS` _will_ be set for most people because the R binary CRAN supplies _is_ compiled with their version of clang. So your package will fail to compile if MacOS users try to compile it with the Xcode clang. See https://stackoverflow.com/questions/43595457/alternate-compiler-for-installing-r-packages-error-installing-rjava/43943631#43943631 for an example of an error caused by this same issue.

**Comment by jonclayden** [comment] 2017-09-13 16:49
@muschellij2 Your second point is only true if the user has also installed `clang` 4.0.0 from CRAN, in addition to running the installer — which is recommended for this reason, but no doubt plenty of users don't see or follow that recommendation.

**Comment by muschellij2** [comment] 2017-09-13 16:50
So is there any consensus what to do here on Travis?

**Comment by jonclayden** [comment] 2017-09-13 16:51
For `mmand` in particular I've just committed a `configure` script which should resolve the issue.

**Closed** 2017-09-13 19:37 UTC
